name: qbt
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - name: vcpkg
      run: |
        cd C:\vcpkg
        git pull
        bootstrap-vcpkg.bat -disableMetrics
        vcpkg install libiconv:x64-windows-static-release qtbase:x64-windows-static-release qtsvg:x64-windows-static-release qttools:x64-windows-static-release --clean-after-build --no-binarycaching
    - name: boost
      run: |
        aria2c https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.7z -d C:
        7z x C:\boost_1_81_0.7z -oC:\
    - name: libtorrent
      run: |
        git clone --depth 1 --branch RC_1_2 https://github.com/arvidn/libtorrent C:\libtorrent
        cd C:\libtorrent
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\boost_1_81_0 -DBUILD_SHARED_LIBS=OFF -Dstatic_runtime=ON -Ddeprecated-functions=OFF -DCMAKE_INSTALL_PREFIX=C:\libtorrent_install -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-release
        cmake --build build
        cmake --install build
    - name: qbittorrent
      run: |
        git clone --depth 1 --branch v4_5_x https://github.com/qbittorrent/qBittorrent C:\qbittorrent
        cd C:\qbittorrent
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\boost_1_81_0 -DMSVC_RUNTIME_DYNAMIC=OFF -DQT6=ON -DSTACKTRACE=OFF -DLibtorrentRasterbar_DIR=C:\libtorrent_install\lib\cmake\LibtorrentRasterbar -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-release
        cmake --build build
    - uses: actions/upload-artifact@v3
      with:
        name: qbittorrent
        path: C:\qbittorrent\build\qbittorrent.exe
