name: Build qBittorrent Static with Qt6 (v5_0_x)

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.bat

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install qt6-base:x64-windows-static
        ./vcpkg/vcpkg install qt6-tools:x64-windows-static
        ./vcpkg/vcpkg install qt6-svg:x64-windows-static
        ./vcpkg/vcpkg install libtorrent:x64-windows-static --head

    - name: Clone qBittorrent source (v5_0_x branch)
      run: |
        git clone --branch v5_0_x https://github.com/qbittorrent/qBittorrent.git
        cd qBittorrent
        git submodule update --init

    - name: Configure qBittorrent with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_TOOLCHAIN_FILE="$pwd/../vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DQT6=ON `
          -DSTATIC=ON
      shell: pwsh

    - name: Build qBittorrent
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: qBittorrent-static
        path: build/src/Release/qbittorrent.exe
